### ISSUE TITLE
only "" should give error "command not found". Our minishell does nothing.

### ISSUE THREAD

**Issue by srondss** [Naji-k/minishell#111]
I give you empty command but command still exists. 
It just has command with string = '\0'.
So should return command not found.
 
![Screenshot 2023-08-29 at 21 01 50](https://github.com/Naji-k/minishell/assets/95218070/350d9555-b207-4a75-836b-3b8ed4d2a7e8)

here is bash example:
![Screenshot 2023-08-29 at 21 04 17](https://github.com/Naji-k/minishell/assets/95218070/f1fae1d0-4dd9-4ad1-904f-9c20fadcf542)

**Comment by Naji-k** [comment]
This issue happened while handling issue #110 , The problem came from the expansion part, 
if there is no explanation like `$ASD`, just delete the node. Do not create an empty node,

the problem is when the input is "" => i am receiving `cmd[0]='\0'` it should be deleted not empty 
also when the input is not exist $NON_EXIST also i am receiving `cmd[0]='\0'`

test cases in bash: 
```
$NON
$NON ls 
"" ls
"" echo hey
```

<img width="468" alt="Screenshot 2023-08-31 at 3 05 00 AM" src="https://github.com/Naji-k/minishell/assets/22378421/ca1de6f4-508d-4e41-9624-1111fc739c60">
